set nocompatible
set number
set relativenumber
set hidden
set nowrap
set mouse=a
set clipboard=unnamedplus
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set ignorecase
set smartcase
set incsearch
set hlsearch
set updatetime=300
set timeoutlen=300

inoremap kj <Esc>

let mapleader=" "

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>ev :e ~/.vimrc<CR>
nnoremap <leader>sv :source ~/.vimrc<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

set noerrorbells
set scrolloff=10
set splitbelow
set splitright

" Ice + Rose highlight overrides (avoid orange/yellow defaults)
syntax on
set termguicolors

" Readable comments - cyan
autocmd ColorScheme * highlight Comment guifg=#6EC6B8 ctermfg=Cyan cterm=italic gui=italic
highlight Comment guifg=#6EC6B8 ctermfg=Cyan cterm=italic gui=italic

" Markdown headings - ice blue instead of magenta
highlight markdownH1 guifg=#A0E2FF ctermfg=Cyan gui=bold
highlight markdownH2 guifg=#A0E2FF ctermfg=Cyan gui=bold
highlight markdownH3 guifg=#8DD6F2 ctermfg=Cyan gui=bold
highlight markdownH4 guifg=#8DD6F2 ctermfg=Cyan
highlight markdownH5 guifg=#8DD6F2 ctermfg=Cyan
highlight markdownH6 guifg=#8DD6F2 ctermfg=Cyan
highlight markdownHeadingDelimiter guifg=#A0E2FF ctermfg=Cyan gui=bold

" Markdown links/URLs - warm gold instead of purple
highlight markdownUrl guifg=#E3B34F ctermfg=Yellow gui=underline
highlight markdownLink guifg=#E3B34F ctermfg=Yellow
highlight markdownLinkText guifg=#A0E2FF ctermfg=Cyan
highlight Underlined guifg=#E3B34F ctermfg=Yellow gui=underline
highlight LineNr guifg=#9BAEC8
highlight CursorLineNr guifg=#A0E2FF gui=bold
highlight Keyword guifg=#8DD6F2
highlight Statement guifg=#8DD6F2
highlight Type guifg=#8DD6F2

" Vim options (like 'number', 'relativenumber') - contrast with statements
highlight vimOption guifg=#EBBCBA ctermfg=LightRed

" Vim highlight group names (like 'EndOfBuffer', 'Comment')
highlight vimHighlightGroup guifg=#E3B34F ctermfg=Yellow

" Color values in highlight commands
highlight vimString guifg=#A7DCA2 ctermfg=LightGreen
highlight PreProc guifg=#A0E2FF
highlight Function guifg=#E6E7E9

" File picker / netrw readability
highlight Directory guifg=#8DD6F2
highlight NetrwDir guifg=#8DD6F2
highlight NetrwPlain guifg=#9BAEC8
highlight CursorLine guibg=#2A2E33

" Visual selection - dark bg with readable text
highlight Visual guifg=#E6E7E9 guibg=#3A4550
highlight VisualNOS guifg=#E6E7E9 guibg=#3A4550

" Empty line tildes (~)
highlight NonText guifg=#2A2E33
highlight EndOfBuffer guifg=#2A2E33

" Popup menu (completion/select lists)
highlight Pmenu guifg=#E6E7E9 guibg=#2A2E33
highlight PmenuSel guifg=#1e1e1e guibg=#8DD6F2
highlight PmenuSbar guibg=#2A2E33
highlight PmenuThumb guibg=#8DD6F2

" Fix purple control-key / special-key highlights
highlight SpecialKey guifg=#9BAEC8 ctermfg=Grey
highlight Special    guifg=#9BAEC8 ctermfg=Grey

" Fix dark pink hex colors / constants
highlight Constant guifg=#EBBCBA ctermfg=LightRed
highlight Number guifg=#EBBCBA ctermfg=LightRed

" Bracket matching - use yellow/orange instead of bright cyan
highlight MatchParen guifg=#E3B34F guibg=NONE gui=bold ctermfg=Yellow cterm=bold
